# Python Functions

This notebook introduces Python functions in a simple, beginner-friendly way. You will learn how to define functions, pass different types of arguments, return values, work with iterators and generators, and use lambda functions with Pandas.

## Learning goals
- Understand the basic structure of a function
- Use positional, default, variable-length, and keyword arguments
- Learn the difference between printing and returning values
- Use iterators and generators for memory-friendly processing
- Apply lambda functions with Pandas

Each example is small and written so a student can run it step by step.

## 1. Structure of a Function

A function is a reusable block of code. It helps us avoid repetition and makes programs easier to read and maintain.

In this section, we will see:
- how to define a function
- how to call a function
- how to use a default argument

In [ ]:
def welcome_message():
    print("Hello, user!")

# A function must be called to run its code.
welcome_message()

In [ ]:
welcome_message()

hello user

In [ ]:
def welcome_message(user="student"):
    print(f"Hello, {user}!")

In [ ]:
welcome_message("Phitron")

hello None

In [ ]:
def adder(a, b):
    """Return the sum of two numbers.

    Parameters:
        a: first number
        b: second number
    """
    return a + b

In [ ]:
m = adder(10, 30) * 5
print(m)

200

In [ ]:
help(adder)

Help on function adder in module __main__:

adder(a, b)
    add two numbers

    a-> int
    b->int

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

## 2. Different Types of Arguments

Functions can accept values in different ways. Here we will learn about positional arguments, variable-length arguments, default arguments, and keyword arguments.

In [ ]:
def show_three_values(a, b, c):
    print(f"a = {a}, b = {b}, c = {c}")

show_three_values(10, 30, 20)

10,30,20

In [ ]:
def show_all_values(*args):
    for value in args:
        print(value)

show_all_values(10, 30, 20, 40)

10
30
20
40

In [ ]:
def show_default_values(a=10, b=30, c=10):
    print(f"a = {a}, b = {b}, c = {c}")

show_default_values()

10,30,10

In [ ]:
def show_keyword_values(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

show_keyword_values(a=10, b=30, c=40, n_estimator=50)

a: 10
b: 30
c: 40
n_estimator: 50

## 3. Return Values

A function can either print a result or return it. Returning a value is more useful when we want to use that result later in our program.

In [ ]:
def welcome_message():
    print("Hello, user!")

print(type(welcome_message()))

hello user
<class 'NoneType'>

In [ ]:
def add_numbers(a, b):
    return a + b

print(type(add_numbers(10, 20)))

<class 'int'>

In [ ]:
def add_numbers(a, b):
    return a + b

print(type(add_numbers(10.5, 20)))

<class 'float'>

In [ ]:
def welcome_message(user="student"):
    return f"Hello, {user}!"

print(type(welcome_message()))

<class 'str'>

## 4. Iterators and Generators

Iterators let us step through values one at a time. Generators are a memory-friendly way to produce values only when needed.

In [ ]:
values = {10, 20, 30, 40, 50}
value_iterator = iter(values)

print(next(value_iterator))
print(next(value_iterator))
print(next(value_iterator))
print(next(value_iterator))
print(next(value_iterator))

print("All values in the set:")
for value in values:
    print(value)

50
20
40
10
30
50
20
40
10
30

## 5. Generators

A generator uses `yield` to create values one at a time. This is helpful when we work with large data because it avoids loading everything into memory at once.

In [ ]:
data = [x for x in range(500)]  # Example dataset

def data_loader(chunk_size, data):
    for start in range(0, len(data), chunk_size):
        yield data[start:start + chunk_size]

loader = data_loader(5, data)

print(next(loader))
print(next(loader))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

## 6. Lambda, Map, and Apply

Lambda functions are short, anonymous functions. They are often used with `map()` or Pandas `apply()` when we need a small transformation.

In [ ]:
import pandas as pd

# Convert temperature values from Fahrenheit to Celsius.
df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})
df

df['temperature (C)'] = df['temperature (F)'].apply(lambda x: (x - 32) * 5 / 9)
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [ ]:
def pair_values(a, b):
    return [a, b]

print(type(pair_values(10.5, 20)))

# Unpack the returned list into two variables.
x, y = pair_values(10.5, 20)
print(y)

<class 'list'>
20

In [ ]:
import pandas as pd

# Example of transforming a column with lambda and apply.
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})
df

df['A'] = df['A'].apply(lambda x: x ** 0.5)
df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [ ]:
import pandas as pd

# Create a simple feature from a numeric column.
df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x > 500 else 0)
df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1

## Summary

In this notebook, we learned the core ideas behind Python functions.

### Key takeaways
- Functions help organize code and reuse logic.
- Arguments can be positional, default, variable-length, or keyword-based.
- A function can print something or return a value for later use.
- Iterators and generators help process values step by step.
- Lambda functions are useful for short transformations in Pandas.

### Practice suggestion
Try changing the argument values, chunk size, and Pandas data to see how the output changes.